In [7]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


Cell 1 — Create Matrix A

In [8]:
# My Student ID = 0432320005101180

d1 = 0   # Last digit
d2 = 8   # Second last digit

# Create Matrix A
A = np.array([
    [d1 + 1, d2 + 1],
    [2 * d1, d2 + 2]
], dtype=float)

print("Matrix A:")
print(A)

Matrix A:
[[ 1.  9.]
 [ 0. 10.]]


Cell 2 — Analyze Matrix A

In [9]:
# Shape
print("Shape of A:", A.shape)

# Determinant
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# Rank
rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)

# Eigenvalues
eigen_A = np.linalg.eigvals(A)
print("Eigenvalues of A:", eigen_A)

# Inverse
if det_A != 0:
    inverse_A = np.linalg.inv(A)
    print("Inverse of A:")
    print(inverse_A)
else:
    print("A has no inverse.")

Shape of A: (2, 2)
Determinant of A: 10.000000000000002
Rank of A: 2
Eigenvalues of A: [ 1. 10.]
Inverse of A:
[[ 1.  -0.9]
 [ 0.   0.1]]


Cell 3 — Create Matrix B

In [10]:
#I will change one element only.

#I chose the first row, first column and added +1.


# Make a copy of A
B = A.copy()

# Add +1 to the first element
B[0, 0] = B[0, 0] + 1

print("Matrix B:")
print(B)

print("\nChanged element: A[0,0]")
print("Added +1 to the first element.")

Matrix B:
[[ 2.  9.]
 [ 0. 10.]]

Changed element: A[0,0]
Added +1 to the first element.


Cell 4 — Analyze Matrix B

In [11]:
# Shape
print("Shape of B:", B.shape)

# Determinant
det_B = np.linalg.det(B)
print("Determinant of B:", det_B)

# Rank
rank_B = np.linalg.matrix_rank(B)
print("Rank of B:", rank_B)

# Eigenvalues
eigen_B = np.linalg.eigvals(B)
print("Eigenvalues of B:", eigen_B)

# Inverse
if det_B != 0:
    inverse_B = np.linalg.inv(B)
    print("Inverse of B:")
    print(inverse_B)
else:
    print("B has no inverse.")

Shape of B: (2, 2)
Determinant of B: 20.000000000000007
Rank of B: 2
Eigenvalues of B: [ 2. 10.]
Inverse of B:
[[ 0.5  -0.45]
 [ 0.    0.1 ]]


Cell 5 — Comparison & Explanation

In [12]:
print("===== Comparison of A and B =====")

print("Determinant of A:", det_A)
print("Determinant of B:", det_B)

print("Rank of A:", rank_A)
print("Rank of B:", rank_B)

print("Eigenvalues of A:", eigen_A)
print("Eigenvalues of B:", eigen_B)

===== Comparison of A and B =====
Determinant of A: 10.000000000000002
Determinant of B: 20.000000000000007
Rank of A: 2
Rank of B: 2
Eigenvalues of A: [ 1. 10.]
Eigenvalues of B: [ 2. 10.]


1. How did the determinant change and why?

The determinant changed from 10 to 20. This happened because we increased the first element of the matrix by 1.

2. Did the rank change? Explain.

No, the rank did not change. Both matrices have rank 2, because both matrices have two independent rows/columns.

3. How did the eigenvalues respond to the value change?

The eigenvalues changed from 1 and 10 to 2 and 10. The first eigenvalue increased because we changed the first diagonal value.

4. Is B easier or harder to invert than A? Why?

Both A and B are easy to invert because their determinants are not zero. B has determinant 20, which is farther from zero than A's determinant 10, so B is generally more stable/easier to invert numerically.