In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
sclar= 4.3
arr = np.array([1.2, -2.5, 3.8, -4.1, 5.6, -6.7, 7.9, 8.4],dtype=float)
sqrt_values = np.sqrt(arr)
abs_values=np.abs(arr)
exp_values=np.exp(arr)
log_values=np.log(arr)
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
clipped=np.clip(arr/10,-1,1)
asin_values=np.arcsin(np.clip(arr/np.max(clipped),-1,1))
acos_values=np.arccos(np.clip(arr/np.max(clipped),-1,1))
atan_values=np.arctan(clipped)



print("add: \n",arr+sclar)
print("sub: \n",arr-sclar)
print("mul: \n",arr*sclar)
print("div: \n",arr/sclar)
print("sqrt: ",sqrt_values)
print("abs: ",abs_values)
print("exp: ",exp_values)
print("log: ",log_values)
print("sin: ",sin_values)
print("cos: ",cos_values)
print("tan: ",tan_values)
print("asin: ",asin_values)
print("acos: ",acos_values)
print("atan: ",atan_values)


add: 
 [ 5.5  1.8  8.1  0.2  9.9 -2.4 12.2 12.7]
sub: 
 [ -3.1  -6.8  -0.5  -8.4   1.3 -11.    3.6   4.1]
mul: 
 [  5.16 -10.75  16.34 -17.63  24.08 -28.81  33.97  36.12]
div: 
 [ 0.27906977 -0.58139535  0.88372093 -0.95348837  1.30232558 -1.55813953
  1.8372093   1.95348837]
sqrt:  [1.09544512        nan 1.94935887        nan 2.36643191        nan
 2.81069386 2.89827535]
abs:  [1.2 2.5 3.8 4.1 5.6 6.7 7.9 8.4]
exp:  [3.32011692e+00 8.20849986e-02 4.47011845e+01 1.65726754e-02
 2.70426407e+02 1.23091190e-03 2.69728233e+03 4.44706675e+03]
log:  [0.18232156        nan 1.33500107        nan 1.7227666         nan
 2.06686276 2.12823171]
sin:  [ 0.93203909 -0.59847214 -0.61185789  0.81827711 -0.63126664 -0.40484992
  0.99894134  0.85459891]
cos:  [ 0.36235775 -0.80114362 -0.79096771 -0.57482395  0.77556588  0.91438315
 -0.04600213 -0.51928865]
tan:  [  2.57215162   0.7470223    0.77355609  -1.42352648  -0.81394328
  -0.44275742 -21.71511268  -1.64571073]
asin:  [ 1.57079633 -1.57079633  1.5

/tmp/ipykernel_949/4258479037.py:3: RuntimeWarning: invalid value encountered in sqrt
  sqrt_values = np.sqrt(arr)
/tmp/ipykernel_949/4258479037.py:6: RuntimeWarning: invalid value encountered in log
  log_values=np.log(arr)


In [25]:
matrix = np.array([[1.5,-2.3,3.7],[-4.2,5.1,-6.8],[7.4,-8.9,9.2],[-1.7,2.6,-3.5]])
sin_values=np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
sin_values=np.arcsin(np.clip(matrix/np.max(matrix),-1,1))
acos_values=np.arccos(np.clip(matrix/np.max(matrix),-1,1))
atan_values=np.arctan(matrix)
exp_values=np.exp(matrix)
log_values=np.log(matrix)
log_values10=np.log10(matrix)
abs_values=np.abs(matrix)
sqrt_values=np.sqrt(matrix)
sqaure=np.square(matrix)
cube_root=np.cbrt(matrix)
rem_values=np.remainder(matrix,3)
round_values=np.round(matrix)
floor_values=np.floor(matrix)
ceil_values=np.ceil(matrix)

print("sin:\n ",sin_values)
print("cos:\n ",cos_values)
print("tan: \n",tan_values)
print("asin: \n",asin_values)
print("acos: \n",acos_values)
print("atan:\n ",atan_values)
print("exp: \n",exp_values)
print("log: \n",log_values)
print("log: \n",log_values10)
print("abs: \n",abs_values)
print("sqrt: \n",sqrt_values)
print("Sqaure: ",sqaure)
print("CubeRoot: ",cube_root)
print("rem:\n ",rem_values)
print("round:\n ",round_values)
print("floor:\n ",floor_values)
print("ceil: \n",ceil_values)


sin:
  [[ 0.16377463 -0.25268026  0.41389001]
 [-0.47408184  0.58757917 -0.83177845]
 [ 0.93457701 -1.31472027  1.57079633]
 [-0.18585066  0.28651258 -0.39026638]]
cos:
  [[ 0.0707372  -0.66627602 -0.84810003]
 [-0.49026082  0.37797774  0.86939749]
 [ 0.43854733 -0.86543521 -0.97484362]
 [-0.12884449 -0.85688875 -0.93645669]]
tan: 
 [[14.10141995  1.11921364  0.62473308]
 [-1.77777977 -2.44938942 -0.56833998]
 [ 2.04928417  0.57892359 -0.22864171]
 [ 7.69660214 -0.60159661 -0.37458564]]
asin: 
 [ 1.57079633 -1.57079633  1.57079633 -1.57079633  1.57079633 -1.57079633
  1.57079633  1.57079633]
acos: 
 [[1.4070217  1.82347658 1.15690632]
 [2.04487816 0.98321716 2.40257477]
 [0.63621932 2.88551659 0.        ]
 [1.75664698 1.28428375 1.96106271]]
atan:
  [[ 0.98279372 -1.16066899  1.3068326 ]
 [-1.33705315  1.37717433 -1.42478407]
 [ 1.43647488 -1.45890606  1.46252574]
 [-1.03907226  1.20362249 -1.29249667]]
exp: 
 [[4.48168907e+00 1.00258844e-01 4.04473044e+01]
 [1.49955768e-02 1.64021907e

/tmp/ipykernel_949/1925853998.py:9: RuntimeWarning: invalid value encountered in log
  log_values=np.log(matrix)
/tmp/ipykernel_949/1925853998.py:10: RuntimeWarning: invalid value encountered in log10
  log_values10=np.log10(matrix)
/tmp/ipykernel_949/1925853998.py:12: RuntimeWarning: invalid value encountered in sqrt
  sqrt_values=np.sqrt(matrix)


In [37]:
matrix = np.array([[1.5,-2.3,3.7,4.2],[-4.2,5.1,-6.8,7.3]])


random_matrix = np.random.uniform(-10,10,(3,4))
print("random: ",random_matrix)
max_value=np.max(matrix)
max_index=np.argmax(matrix)

min_value=np.min(matrix)
min_index=np.argmin(matrix)

sum_values=np.sum(matrix)
mean_values=np.mean(matrix)
median_value=np.median(matrix)
std_dev=np.std(matrix)




print("max: \n",max_value)
print("max_IN: \n",max_index)
print("min:\n ",min_value)
print("min_IN:\n ",min_index)
print("sum: \n",sum_values)
print("mean:\n ",mean_values)
print("median: \n",median_value)
print("std: \n",std_dev)
print("Variance:", np.var(matrix))





random:  [[-5.56577259  0.07847916 -9.34701061 -2.33111867]
 [-5.50989121 -0.50759574  3.85128819  1.62353402]
 [ 1.40114537 -2.58574109 -2.03363084  0.55388752]]
max: 
 7.3
max_IN: 
 7
min:
  -6.8
min_IN:
  6
sum: 
 8.5
mean:
  1.0625
median: 
 2.6
std: 
 4.650520804168067
Variance: 21.627343749999998
